{
 "title": "Data Drift Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT drift_detected AS \"dataset drift\", created_time FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT drift_score AS \"Drift Score\", created_time FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "# drifted features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_drifted_columns FROM drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_columns FROM drift_metrics LIMIT 50 "
    }
   ]
  }
 ]
}